### ISSUE TITLE
What about super-interested folks wanting internal doc access?

### ISSUE THREAD

**Issue by christrotter** [trussworks/distributed-playbook#5]
My colleague and I have been excitedly trawling through the playbook, but are very saddened that things like TDR-0003, TDR-0012, and 'healthy work habits doc' and other budget-ey stuff are behind lock and key.  While we understand the necessity, we are still very saddened.

We are trying to build out a similar framework/new management paradigm at our company - would it be possible for us to meet and chat with a Trussel for Q&A and inspiration?  Or could those docs be genericized and published?

**Comment by willowbl00** [comment]
Hi @christrotter! We have a plan to slowly roll out our TDRs to the public as relevant and safe (the first step of which will be to roll out our Trussels' Guide to Truss), but in the meantime I'd reach out to @ferlatte to see about having a Trussel come talk at your organization about our TDR (and ADR) processes.

**Comment by ferlatte** [comment]
Hey @christrotter FYI, most of this content has moved over to the Trussels' Guide. Happy to chat anytime about this, and this project is being archived as a result.
